name: Development workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Here the environment variable is declared in workflow level
env:
  PROJECT_NAME: My_Project_Name
  #PROJECT_FOLDER: ${{ github.action_path }} 
  ORCH_CLIENT_ID: ${{ secrets.APP_ID }} #create in repository
  ORCH_SECRET: ${{ secrets.APP_PWD }} #create in repository
  #GH_TOKEN: ${{ github.token }}
 

jobs:
  cleaner:
    runs-on:  ubuntu-latest
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "$ {{ github.workspace }}"

  analyze-project:
    needs: cleaner
    runs-on: windows-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v4
#      - name: Analyze project for errors  
#        shell:  pwsh
#        run:  ${{ github.workspace }}\.entities\CLI\tools\uipcli.exe package analyze "${{ github.workspace }}\project.json" --analyzerTraceLevel "Error"  --resultPath "${{ github.workspace }}\validate.json" --orchestratorUrl "https://staging.uipath.com/" --orchestratorTenant "DefaultTenant" --orchestratorApplicationScope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Monitoring OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Administration OR.Analytics OR.Audit OR.Hypervisor OR.License OR.Machines OR.ML OR.Queues OR.Robots OR.Settings OR.Tasks OR.TestDataQueues OR.Users OR.Webhooks" --orchestratorAccountForApp "lucas_antunes_tam" --orchestratorApplicationId ${{env.ORCH_CLIENT_ID}} --orchestratorApplicationSecret ${{env.ORCH_SECRET}} --orchestratorFolder "teste"
#      - name: Upload Analyzer File
#        uses: actions/upload-artifact@v4
#        with: 
#          name: ValidationFile
#          path: validate.json
      
  build-uipath-nuget-package:
    needs: analyze-project
    runs-on: windows-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v4
      - name: Build nuget package 
        shell:  pwsh
        run:  |
          ${{ github.workspace }}\.entities\CLI\tools\uipcli.exe package pack "${{ github.workspace }}\project.json" -o "${{ github.workspace }}\package" --autoVersion --outputType "Tests" --libraryOrchestratorUrl "https://staging.uipath.com/" --libraryOrchestratorTenant "DefaultTenant" --libraryOrchestratorApplicationId ${{env.ORCH_CLIENT_ID}} --libraryOrchestratorApplicationSecret ${{env.ORCH_SECRET}} --libraryOrchestratorAccountForApp "lucas_antunes_tam" --libraryOrchestratorApplicationScope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Monitoring OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Administration OR.Analytics OR.Audit OR.Hypervisor OR.License OR.Machines OR.ML OR.Queues OR.Robots OR.Settings OR.Tasks OR.TestDataQueues OR.Users OR.Webhooks" --libraryOrchestratorFolder "teste"
          ls ${{ github.workspace }}\package
      - name: Upload UiPath Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: Artifacts
          path: package/*.*


  publish-uipath-nuget-package:
    needs:  build-uipath-nuget-package
    runs-on:  windows-latest
    steps:
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      - name: Check out repository code 
        uses: actions/checkout@v4
      - name: Publish Nuget Package to DEV
        shell:  pwsh
        run:  ${{ github.workspace }}\Scripts\PublishPackage.ps1 ${{ github.workspace }}\package\*.nupkg  ${{env.ORCH_CLIENT_ID}} ${{env.ORCH_SECRET}}

  add-process-to-folder:
    needs:   publish-uipath-nuget-package
    runs-on:  windows-latest
    steps:
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      - name: Add Process to Folder
        shell:  pwsh
        run:  ${{ github.workspace }}\scripts\AddProcessToDev.ps1

  test-uipath-published-package:
    needs:  add-process-to-folder
    runs-on:  windows-latest
    steps:
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      - name: Get Test Cases
        shell:  pwsh
        run:  ${{ github.workspace }}\scripts\GetTests.ps1 
      - name: Upload Test Cases
        uses: actions/upload-artifact@v4
        with: 
          name: Tests
          path: TestReport.csv
      - name: Download Test Cases
        uses: actions/download-artifact@v4
        with: 
          name: Tests
      - name: Run Test Cases
        shell:  pwsh
        run:  ${{ github.workspace }}\scripts\StartTests.ps1 
